coverage:
  round: up
  range: 50..80

  status:
    project: # settings affecting project coverage
      default:
        enabled: yes
        target: auto # auto % coverage target
        threshold: 5%  # allow for 5% reduction of coverage without failing

    # do not run coverage on patch nor changes
    patch:
      default:
        enabled: false
    changes: no